### ISSUE TITLE
Anonymous User Issue

### ISSUE THREAD

**Issue by frozendnn** [DNNCommunity/Dnn.CommunityForums#204]
See here: 
https://github.com/ActiveForums/ActiveForums/issues/62

This has already been resolved. Someone please redo/pull this here. I wish I knew how to otherwise I would have. 

Thank you.

**Comment by WillStrohl** [comment]
Thank you for posting this issue.  I just read through the original post, and I'd have the same concerns that Jason did... It's not really a common use case to allow anonymous posting.  Honestly, I didn't even know this forums module ever allowed that.  

My personal opinion is that we'll also continue to not remove that feature since it's currently being used, but I'm not sure there is any benefit to the rest of the code base and ecosystem to expand on that functionality.  As it is, we have major issues with spam on any website that exposes any kind of forum functionality.  That will continue to be one of our highest priorities.  

In the meantime, if you'd like there to be more work done on that featureset moving forward, I'm sure none of us would have a problem accepting those updates as a new `Pull Request`, with a well-documented `Issue` here.  

As always, I'll continue to defer to what the majority in the community think as well.  So, if we have a consensus to do otherwise, I won't stand in the way of that either.  :) 

So, we'll keep this issue open for now to allow others to express their opinions as well.

**Comment by frozendnn** [comment]
Have a feature and not using it is better than not having an option. I do allow users to post anonymously on my forums. We have a very open and brutal conversations. So much that we have had law suits and once Secret Service contacted me. It was fun, How many people get to say that? All that said...thank you for keeping an open mind and keeping this issue open. I appreciate it.

**Comment by frozendnn** [comment]
Dang! Mine was set to display name. Arent usernames also email addresses? My DNN install version is 7.3. I cannot upgrade it because all the errors. I will try it out.

p.s. anyone want to help me with the upgrade? I will pay ofcourse.
