### ISSUE TITLE
HiddenStats ??

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#461]
## Please summarize your question in one sentence
The main template contains a hidden span containing this:

`<span class="afhiddenstats">2 Topics and 2 Replies and 0 Subscribers</span>`

## Give a more extended description
I have no idea WHY that's in there as it's essentially a repetition of this, a few lines later.
And it's hidden using CSS.

```
<span class="af-colstats_responsive">
	<i class="fa fa-files-o fa-fw fa-grey"></i>&nbsp;[TOTALTOPICS] 
	<i class="fa fa-reply fa-fw fa-grey"></i>&nbsp;[TOTALREPLIES]
	<i class="fa fa-envelope-o fa-fw fa-grey"></i>&nbsp;[FORUMSUBSCRIBERCOUNT]
</span>
```

In full:

```
<table>
		<tr>
			<td rowspan="2" class="afsubject">
				<span class="afhiddenstats">[TOTALTOPICS] [RESX:TOPICSHEADER] and [TOTALREPLIES] [RESX:REPLIESHEADER] and [FORUMSUBSCRIBERCOUNT] [RESX:SUBSCRIBERS]</span>
				<span class="aftopictitle">[FORUMNAME]</span>
				<span class="af-colstats_responsive">
					<i class="fa fa-files-o fa-fw fa-grey"></i>&nbsp;[TOTALTOPICS] 
					<i class="fa fa-reply fa-fw fa-grey"></i>&nbsp;[TOTALREPLIES]
					<i class="fa fa-envelope-o fa-fw fa-grey"></i>&nbsp;[FORUMSUBSCRIBERCOUNT]
				</span>
				<span class="aftopicsubtitle">[FORUMDESCRIPTION]</span>
				<div class="af_lastpost_responsive" style="white-space:nowrap;">[LASTPOSTSUBJECT:25]<br />[RESX:BY] [DISPLAYNAME]<br />[LASTPOSTDATE]</div>
			</td>
		</tr>
	</table>
```
I guess it can be removed in the updated template, right?
Opinions?

@WillStrohl @johnhenley ?

**Comment by johnhenley** [comment]
I wondered the same thing when I was working on #238, and I just added the subscriber counts to the existing structure.
To me, it *looks* like the stats columns are duplicated because there is a "responsive" version that is perhaps not shown on smaller devices? And the "hidden" stats are there for search engines? 

I dug way back into the former code repository and found that this was added here:
https://github.com/ActiveForums/ActiveForums/commit/a181c91462f96ccd9ab6f4a45bdd1453a6ad9ede#diff-10b79cc39b760b9073a428381780921e4d7992f586131753f4dde80e80f009c6

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/704d4802-b782-45cd-9762-e44d239dabe3)

It makes no sense to me, since `display:none` doesn't remove it from the markup so it would still be visible to a search engine. I think we can clean it up if you want.

**Comment by Timo-Breumelhof** [comment]
I agree, I'll clean it up

**Comment by johnhenley** [comment]
> I agree, I'll clean it up

Let me know when you do, since we also need to change the af_grid.cs.ascx/af_grid.cs code a little bit I think.

**Comment by Timo-Breumelhof** [comment]
Fixed with #501

**Comment by johnhenley** [comment]
@Timo-Breumelhof  did you mean to close this one? Don't we still need to fix it, at least at some point? There is code here that needs to be updated as well:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/5b028398-7864-4804-b4a2-99ae4b4e4e80)

**Comment by Timo-Breumelhof** [comment]
@johnhenley my issue was about the "afhiddenstats" css class.
I removed from both module.css and the new template
I think removing the responsive class will break the v7 Theme?
Maybe do that for v 9?

**Comment by johnhenley** [comment]
Should I reopen as a placeholder since it has the context of what new to be addressed?

**Comment by Timo-Breumelhof** [comment]
@johnhenley I'm fine with that and we put everything we find related legacy class related in here?

**Comment by johnhenley** [comment]
Re-opening to work on this in future release.

**Comment by johnhenley** [comment]
@Timo-Breumelhof these were removed in af_grid (used for filtered topics). I will see if they exist anywhere else in code or templates.
