### ISSUE TITLE
Default v7 template  Topic View error in  v8

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#479]
## Describe the bug
The default template for TopicView renders an error in  v8
"object not set to an..."

## Software Versions
- DNN: 09.10.01
- Module: 08.00.00

## To Reproduce
1. Install module v8
2. Set the template /  theme of a forum all to default / legacy
3. Open a topic
4. See the error above

## Expected behavior
It should work ;-)

## Screenshots

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/751fa29a-9b6a-435a-acf6-7a11312911d4)

**Comment by johnhenley** [comment]
@Timo-Breumelhof I have not been able to duplicate this. Can you try it after you've re-sync'd to current dev repo?

**Comment by Timo-Breumelhof** [comment]
@johnhenley Ok I will

**Comment by Timo-Breumelhof** [comment]
@johnhenley tested still the same issue, weird.. 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/ea23cff5-3138-4b94-9b6f-bbf2ec18cfdb)

**Comment by johnhenley** [comment]
> @johnhenley tested still the same issue, weird.. ![image](https://user-images.githubusercontent.com/8999382/270692262-ea23cff5-3138-4b94-9b6f-bbf2ec18cfdb.png)

1. Did you resync your dev branch to include all of the latest pull requests?
2. With "_legacy" theme?

**Comment by Timo-Breumelhof** [comment]
@johnhenley yes I did. I'll try to have another look tomorrow, not sure what's going on..

**Comment by johnhenley** [comment]
@Timo-Breumelhof  I pulled down latest dev branch, installed 07.00.12, set to _default, then installed latest dev, which changed to _legacy. 
This is what I see in topic view:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/3854777f-9205-4bbf-a8c9-58ef3a9b3c7a)

**Comment by johnhenley** [comment]
@Timo-Breumelhof the Template looks different. In yours, the breadcrumb is under the topic. In mine, it's on top. Can you double-check theme, and topicview template for that forum, and send me the template? Do you see anything in admin log? If not, we might need to wrap something to capture the exception to the admin log.

**Comment by johnhenley** [comment]
@Timo-Breumelhof do you want me to update this with our findings? I am putting in a pull request for changes to workaround this, but I want to make sure we have the issues documented.

**Comment by Timo-Breumelhof** [comment]
> @Timo-Breumelhof do you want me to update this with our findings? I am putting in a pull request for changes to workaround this, but I want to make sure we have the issues documented.

please do :-)

**Comment by johnhenley** [comment]
After researching this, it was discovered that the module had been copied in the portal, so there were two module instances. The first has "good" settings, and the second "bad" settings, without any templates, for example:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/d5870672-1919-4e6d-8cd6-571d6594a0c0)

The outcome of this research is three items need to be addressed:
1. Module _should_ still work if no templates are defined, since the default templates are shipped with the module. Updated the template loading logic (#527) to load a default template even if there is no corresponding template record in `activeforums_templates`. Note that the `activeforums_template` table will altogether be removed in an upcoming release when we adopt convention-based templates #477.
2. The forums module does not support import / export, and copying the module is currently not supported. Adding an issue to disable 'add existing module' to try to copy the module. This is a short-term change to protect module from being copied.
3. Adding a longer-term issue to investigate adding import/export and proper copying of the module.
