### ISSUE TITLE
Create Template still creates .txt files

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#528]
## Describe the bug
When I create a new template the file created is a txt file

## Software Versions
- DNN: 08.00.00
- Module: 09.10.02

## To Reproduce
1. Go to the Controlpanel
2. Open Templates
4. Create a new one
5. The created file is a .txt file

(BTW,you can select it as a template)

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/039c2c77-3e56-4845-81fb-8d9b0be98cd7)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/bcb88d02-a257-4680-a810-b4642d6f5d9d)

@johnhenley I'll leave it to you if this is for 8.0.0 or 8.1.0 :-)

**Comment by johnhenley** [comment]
@Timo-Breumelhof I will fix it for 08.00.00

**Comment by johnhenley** [comment]
@Timo-Breumelhof I will fix it for 08.00.00

**Comment by johnhenley** [comment]
@Timo-Breumelhof this was updated in the SQL that saves the template, so that it creates the file with .ascx rather than .txt. If you haven't updated the module (for example, if you are doing either a .dll copy of new binary, or doing a repair install, the SQL updates are not applied). You should probably run the 08.00.00.SqlDataProvider manually to get it updated.
The change was done here.
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/e6ae2c1d-40f8-4e41-b447-aa0daf621f40)

Marking this as closed.

**Comment by Timo-Breumelhof** [comment]
ok thanks, sorry for the wasted brain cycles..
