### ISSUE TITLE
Question: Legacy Templates naming after update

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#590]
## Describe the bug
Question, correct me if I'm wrong :-)

The legacy Template names are numbered after an upgrade.
See:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/683312c5-f766-4a46-b5d0-f4018f672ab9)

Is that needed? It suggests that this is needed, but AFAIK it's not?

## Software Versions
- DNN: 09.11.02
- Module: 08.00.00

## To Reproduce
1. Run 08.00.00 upgrade
2. Open the _legacy templates folder

**Comment by johnhenley** [comment]
@Timo-Breumelhof the number is only appended to the filename if you have multiple templates in the activeforums_templates table with the same name and moduleid. I would assume you are seeing this because you are repeatedly re-installing/upgrading without properly deleting the module beforehand. If you do a fresh install of 7.0.12, and then upgrade to 8.0, you should not see the numbers being appended.

**Comment by Timo-Breumelhof** [comment]
@johnhenley ok thank you for the reply
