### ISSUE TITLE
Creating a new topic is too confusing

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#828]
When I go to create a new topic, using the standard configuration I see a ton of options below the Body text.
After looking carefully I see I can close some sections and then I see this:

![dnnlangmodules dnndev me_es-es_Forums_afv_post_aff_1](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4357679/9c7c5fb2-4062-4de1-8246-58c4949108ca)

I'd say at least it should be shown this way, or maybe even the sections implemented as tabs below the main body

**Comment by johnhenley** [comment]
@vmasanas I did a few tweaks and it now is a bit cleaner, although there is a lot more we can do in the future. For now I think this is "better"?
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/f9cca063-c721-4065-8a5c-ac3f1948e937)

**Comment by johnhenley** [comment]
@Timo-Breumelhof the collapsible section logic I put in for 8.0 uses cookies to track collapsed state:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/e21bf0d3-7401-40ed-bc20-387d6d77f272)
Do you know if that will work for the bootstrap theme since you are doing something different now?

**Comment by vmasanas** [comment]
@johnhenley definetly much better. Thanks!
