### ISSUE TITLE
Smilies look a bit weird

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#829]
When adding a new post I see two groups of icons that look very similar and it's quite confusing.

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4357679/13330acd-c14d-493a-bb1e-e9a3810334d6)

if icons are not something CRITICAL to the publication of a new post they should be hidden and the publication screen should be much simpler and cleaner (think about stackoverflow).

Also the icons on the right of the body text editor should be hidden by default. Maybe open as a menu popup or similar

**Comment by johnhenley** [comment]
The icons on the top/left are "post icons" supposed to reflect the overall tone of the post. 
On the right are "emoticons" (or "smilies") that can be inserted into the text. Those are likely duplicated by functionality in whatever HTML editor you use. 
Both options are configured per forum or forum group--and can be turned off or on depending on the site's objective. 
We have debated removing (#160 and #162) but for now have left them in place since they can be turned off.

**Comment by vmasanas** [comment]
John, I know what the icons are and their purpose. My comment was more in line with what a regular user might think when seing this screen while trying to post on a forum.
