### ISSUE TITLE
Sections are not styled

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#830]
When creating new topics, captions for sections are not properly styled so you don't know what is a caption and what is content.

See on the image below, all captions highlighted in red look exactly the same as the content below.
Consider also the other issue I reported before suggesting rethinking this design (maybe changing it to tabs).

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4357679/f9092e66-1639-4477-8fd2-f21e80e9a297)

**Comment by johnhenley** [comment]
@vmasanas I created this mess I think by enabling more features by default. Most of these (polls, tags, categories, etc.) used to be hidden because they were not enabled when forums are initially installed. I found that people were asking for "new features" which actually already existed but just were not well-documented or disabled by default. By turning them all on by default that leads to more confusion I guess. We should probably go back to disabled by default and then re-address as part of enhancing configuration during install (#725) and providing a simple theme (#426).
