### ISSUE TITLE
Email Sending Error: Portal Specific SMTP setting ignored

### ISSUE THREAD

**Issue by euclid-mark** [DNNCommunity/Dnn.CommunityForums#96]
## Please summarize your question in one sentence

Emails from Active Forum are not sending using the portal specific SMTP configurations

## Give a more extended description
I discovered that emails sent via Active Forum are not using the portal specific SMTP configuration. 

The emails were working fine in the past, but stopped recently. After investigation I found that the reason they stopped working is the host SMTP server configuration was not longer configured correctly to send out emails. This issue is not related to a recent upgrade to DNN 9.9.1.

DNN 9.9.1 install with version 6.6.0 of Active Forums installed.

## Steps to reproduce (if needed)

Using the tip from Timo-Breumelhof I setup the installation to store eml files in a local server pickup folder. I configured the portal SMTP to use the localhost configuration. Emails were not sent to the pickup folder. When I configured the host SMTP server with the same configuration, the emails were saved into the pickup folder. 

This is an indication that active forum is not looking at the portal SMTP server settings if they are configured.

**Comment by Timo-Breumelhof** [comment]
IMO you should first upgrade to the latest version of the forum module as we are using the email functionality and it all seem t work fine.

**Comment by euclid-mark** [comment]
> IMO you should first upgrade to the latest version of the forum module as we are using the email functionality and it all seem to work fine.

Is there a newer version than 6.6.0? If so it is not listed on the releases page.

**Comment by Timo-Breumelhof** [comment]
oh ok you wrote:
"This is an old install of the original Active Forum (version 3 or so)"
So I concluded that you where still on version 3

**Comment by hismightiness** [comment]
E-mail is a difficult thing to troubleshoot, but with a module like this one, if it wasn't working due to the code, it's most likely not going to work for anyone.  As Timo pointed out, the [DNN](https://dnncommunity.org) Community website is running with this module and notifications are sent without issue.  

In looking at the error below, I'd first look into the configuration where the website is hosted.  

`Unable to read data from the transport connection: net_io_connectionclosed`

This message makes me first think that the server may not be configured to properly connect to SendGrid with a TLS connection.   If you are able to manage this server yourself, you can use [IIS Crypto](Unable to read data from the transport connection: net_io_connectionclosed) to check and potentially fix this problem safely.  If you don't have the ability to manage the server, you may want to contact your hosting provider to ensure your hosting plan supports TLS 1.2 (minimum version).  

If this is not the cause, perform the same check in any firewalls you might have (e.g., CloudFlare, Azure WAF, etc.).  You either need to update that to allow this connection and/or review it for any firewall exceptions that might be trapping the e-mails.  

You can also check SendGrid's Suppression menu to see if there are any reasons SendGrid might be blocking e-mails.  This happens more than most of us think.  

![image](https://user-images.githubusercontent.com/938023/135156771-56b97c6a-684f-496b-8e9a-0b37a9fed198.png)

**Comment by Timo-Breumelhof** [comment]
And to add to that.
What I always try is this: https://www.40fingers.net/Blog/ID/95/Testing-DotNetNuke-emails-in-your-development-environment
That way you know if DNN is trying to deliver the emails and the email provider fails or that it's a Modules / DNN config issue.
If they end up in the defined folder, it's most likely an external factor

**Comment by euclid-mark** [comment]
Timo-Breumelhof,

Thanks for this tip. I think I discovered the problem. 

I tested using the local pickup folder at the portal level and it never created the eml file. I then configured the host SMTP server settings and it did create the eml file. That leads me to believe that the AF module is not looking at the portal specific SMTP server settings. It only looks at the host settings. This is a multi-portal install with different websites and SMTP server settings per portal.

**Comment by euclid-mark** [comment]
So next question, can the next update of the module be configured so it will look at the portal specific SMTP settings if those are configured.

**Comment by Timo-Breumelhof** [comment]
It can be but as we are all "volunteers" so we cannot give you any guarantees.
TBH, we start with the issues we or our clients experience in normally.
BTW, can you please change the Title and initial description to what you have found out and add "steps to reproduce"?
That will make it easier for a developer to fix the issue :-)

**Comment by hismightiness** [comment]
Wow... Good catch indeed!  If this is true, then I'm guessing the SMTP code in the module isn't using the DNN API to send e-mails. 🤔

**Comment by euclid-mark** [comment]
@johnhenley Yes we still have several portal specific installations of the forum module. I have been using a workaround of sending everything through the host SMTP setting, but that is causing delivery issues. I have moved a few portals out to their own install if the delivery becomes an issue.

**Comment by johnhenley** [comment]
@euclid-mark: ok. thanks.
